[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "targets/riscv/riscv64-flintos.json"

[target."riscv64-flintos"]
rustflags = [
    "-C", "link-arg=-Tsrc/bootloader/src/riscv/linker.ld",
]
runner = "qemu-system-riscv64 -D qemu.debug -machine virt -bios none -serial mon:stdio -kernel "
#runner = "qemu-system-riscv64 -D qemu.debug -machine virt -bios none -serial mon:stdio -d guest_errors,exec -S -gdb tcp::1234 -kernel "
#runner = "qemu-system-riscv64 -D qemu.debug -machine virt -nographic -bios none -serial mon:stdio -d guest_errors,exec -kernel "
