[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "riscv-flint-os.json"

[target."riscv-flint-os"]
rustflags = [
    "-C", "link-arg=-Tsrc/bootloader/src/riscv/linker.ld",
]
runner = "qemu-system-riscv64 -machine virt -bios none -serial mon:stdio -kernel "
